# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './programa/untitled.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!
import os,sys
from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 781, 561))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tela1 = QtGui.QWidget()
        self.tela1.setObjectName(_fromUtf8("tela1"))
        self.pushButton_4 = QtGui.QPushButton(self.tela1)
        self.pushButton_4.setGeometry(QtCore.QRect(310, 370, 111, 41))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.pushButton_4.clicked.connect(self.executeLaunch)
        self.tabWidget.addTab(self.tela1, _fromUtf8(""))
        self.tela2 = QtGui.QWidget()
        self.tela2.setObjectName(_fromUtf8("tela2"))
        self.frame_2 = QtGui.QFrame(self.tela2)
        self.frame_2.setGeometry(QtCore.QRect(310, 10, 461, 511))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.tabWidget_2 = QtGui.QTabWidget(self.tela2)
        self.tabWidget_2.setGeometry(QtCore.QRect(10, 10, 291, 511))
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.tab)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 40, 241, 311))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_18 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_16.addWidget(self.label_18)
        self.lineEdit_17 = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_17.setObjectName(_fromUtf8("lineEdit_17"))
        self.horizontalLayout_16.addWidget(self.lineEdit_17)
        self.verticalLayout_3.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_12 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_10.addWidget(self.label_12)
        self.lineEdit_11 = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.horizontalLayout_10.addWidget(self.lineEdit_11)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_19 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_17.addWidget(self.label_19)
        self.lineEdit_18 = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_18.setObjectName(_fromUtf8("lineEdit_18"))
        self.horizontalLayout_17.addWidget(self.lineEdit_18)
        self.verticalLayout_3.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_20 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_18.addWidget(self.label_20)
        self.lineEdit_19 = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_19.setObjectName(_fromUtf8("lineEdit_19"))
        self.horizontalLayout_18.addWidget(self.lineEdit_19)
        self.verticalLayout_3.addLayout(self.horizontalLayout_18)
        self.pushButton_2 = QtGui.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(80, 400, 111, 41))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.tabWidget_2.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayoutWidget = QtGui.QWidget(self.tab_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 40, 241, 311))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_13 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_11.addWidget(self.label_13)
        self.lineEdit_12 = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.horizontalLayout_11.addWidget(self.lineEdit_12)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_10 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_8.addWidget(self.label_10)
        self.lineEdit_9 = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.horizontalLayout_8.addWidget(self.lineEdit_9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_11 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_9.addWidget(self.label_11)
        self.lineEdit_10 = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.horizontalLayout_9.addWidget(self.lineEdit_10)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_17 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_15.addWidget(self.label_17)
        self.lineEdit_16 = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.horizontalLayout_15.addWidget(self.lineEdit_16)
        self.verticalLayout_2.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_14 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_12.addWidget(self.label_14)
        self.lineEdit_13 = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.horizontalLayout_12.addWidget(self.lineEdit_13)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_16 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_14.addWidget(self.label_16)
        self.lineEdit_15 = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.horizontalLayout_14.addWidget(self.lineEdit_15)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_15 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_13.addWidget(self.label_15)
        self.lineEdit_14 = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.horizontalLayout_13.addWidget(self.lineEdit_14)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.pushButton = QtGui.QPushButton(self.tab_2)
        self.pushButton.setGeometry(QtCore.QRect(80, 400, 111, 41))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.tabWidget_2.addTab(self.tab_2, _fromUtf8(""))
        self.tabWidget.addTab(self.tela2, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Motion Planning Plot", None))
        self.tela1.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p><p><br/></p></body></html>", None))
        self.pushButton_4.setText(_translate("MainWindow", "Executar", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tela1), _translate("MainWindow", "Conexão", None))
        self.label_18.setText(_translate("MainWindow", "Valor de X", None))
        self.label_12.setText(_translate("MainWindow", "Valor de Y", None))
        self.label_19.setText(_translate("MainWindow", "Valor de Z", None))
        self.label_20.setText(_translate("MainWindow", "Orientação", None))
        self.pushButton_2.setText(_translate("MainWindow", "Executar", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("MainWindow", "Posição cartesiana", None))
        self.label_13.setText(_translate("MainWindow", "Joint 1", None))
        self.label_10.setText(_translate("MainWindow", "Joint 2", None))
        self.label_11.setText(_translate("MainWindow", "Joint 3", None))
        self.label_17.setText(_translate("MainWindow", "Joint 4", None))
        self.label_14.setText(_translate("MainWindow", "Joint 5", None))
        self.label_16.setText(_translate("MainWindow", "Joint 6", None))
        self.label_15.setText(_translate("MainWindow", "Joint 7", None))
        self.pushButton.setText(_translate("MainWindow", "Executar", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("MainWindow", "Juntas", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tela2), _translate("MainWindow", "Planejamento de movimento", None))

    def executeLaunch(self):
       import subprocess 
       return_code = subprocess.call('roslaunch panda_moveit_config demo.launch', shell=True)



if __name__ == '__main__':
    app = QtGui.QApplication(sys.argv)
    window =  QtGui.QMainWindow()
    classe = Ui_MainWindow()
    classe.setupUi(window)
    window.show()
    sys.exit(app.exec_())